## Created by Elia Roysandi Manurun

email: `eliaroysandimanurun@gmail.com`,

instagram: `@eliaroysandi.m`,

github: `https://github.com/Elroy71`

# Prepare the Data

In [47]:
import pandas as pd

In [48]:
df = pd.read_excel('supermarkt_sales.xlsx',skiprows=3)
df_copy = df.copy()

# First Column

In [49]:
df = df.drop('Unnamed: 0', axis=1)

In [50]:
# df.groupby(df['Product line']).sum()
df.groupby(by=['Product line']).sum()

<ipython-input-50-5ea55a7db60c>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(by=['Product line']).sum()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
Product line,,,,,,,,
Electronic accessories,9103.77,971,2587.5015,54337.5315,51750.03,809.523810,2587.5015,1177.2
Fashion accessories,10173.35,902,2585.9950,54305.8950,51719.90,847.619048,2585.9950,1251.2
Food and beverages,9745.54,952,2673.5640,56144.8440,53471.28,828.571429,2673.5640,1237.7
Health and beauty,8337.88,854,2342.5590,49193.7390,46851.18,723.809524,2342.5590,1064.5
Home and lifestyle,8850.71,911,2564.8530,53861.9130,51297.06,761.904762,2564.8530,1094.0
Sports and travel,9460.88,920,2624.8965,55122.8265,52497.93,790.476190,2624.8965,1148.1

In [51]:
df.groupby(df['Product line']).sum()['Total']

<ipython-input-51-333563d52d01>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(df['Product line']).sum()['Total']

Product line
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Food and beverages        56144.8440
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Sports and travel         55122.8265
Name: Total, dtype: float64

In [52]:
df.groupby(df['Product line']).sum()[['Total']].sort_values('Total')

<ipython-input-52-ed0c50789229>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(df['Product line']).sum()[['Total']].sort_values('Total')

                             Total
Product line
Health and beauty       49193.7390
Home and lifestyle      53861.9130
Fashion accessories     54305.8950
Electronic accessories  54337.5315
Sports and travel       55122.8265
Food and beverages      56144.8440

# Second Column

In [64]:
df_copy = df_copy.drop('Unnamed: 0', axis=1)

In [65]:
# The time column is still of type object
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer_type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
 17  hour                     1000 non-null   int64
dtypes: datetime64[ns](1), float64(7), int64(2), object(8)
memory usage: 140.8+ KB

In [66]:
#The data below cannot be converted into hours, because the format has not been changed to datetime
df_copy['hour'] = df['Time'].dt.hour

AttributeError: Can only use .dt accessor with datetimelike values

In [67]:
#change the object data type to datetime with format='%H:%M:%S' then .dt.hour
df_copy['hour'] = pd.to_datetime(df_copy['Time'], format='%H:%M:%S').dt.hour
df_copy

,Invoice ID,Branch,City,Customer_type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2021-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2021-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2021-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2021-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2021-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2021-01-29,13:46:00,Ewallet,40.35,4.761905,2.0175,6.2,13
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2021-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4,17
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2021-02-09,13:22:00,Cash,31.84,4.761905,1.5920,7.7,13
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2021-02-22,15:33:00,Cash,65.82,4.761905,3.2910,4.1,15
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2021-02-18,13:28:00,Cash,618.38,4.761905,30.9190,6.6,13